os:
 - linux
before_script:
 - sudo apt-get update
 - sudo apt-get install qemu
 - sudo apt-get install binutils
 - sudo apt-get install build-essential
 - sudo apt-get install binutils-dev
 - sudo apt-get install libboost-all-dev
script: 
 - cd ./decaf & ./configure --disable-vmi & make
 - cd ./decaf & ./configure --enable-tcg-taint & make
 - cd ./decaf & ./configure & make
language: c
